### ISSUE TITLE
Crash/Exceptions

### ISSUE THREAD

**Issue by ndbn** [DaemonUmbra/Simple-Hammers#11]
MC 1.12.2

```
Time: 1/23/18 11:41 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at daemonumbra.simplehammers.items.hammers.ItemSimpleHammerBase.func_179218_a(ItemSimpleHammerBase.java:63)
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:376)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:320)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:109)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:316)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:641)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

`    public boolean onBlockDestroyed(ItemStack stack, World worldIn, IBlockState state, BlockPos pos, EntityLivingBase entityLiving) {
        if (super.onBlockDestroyed(stack, worldIn, state, pos, entityLiving)) {
            if (isValidStoneOre(state, worldIn, pos) && !entityLiving.isSneaking()) {
                if (!worldIn.isRemote) {
                    RayTraceResult result = rayTrace(worldIn, (EntityPlayer) entityLiving, false);
                    switch (result.sideHit) {`

May be need to check rayTrace result before using. But this crash was not when block destroyed. Sometimes trowned non critical exceptions(see log) :
[2018-01-23-7.log](https://github.com/DaemonUmbra/Simple-Hammers/files/1657606/2018-01-23-7.log)

**Comment by DaemonUmbra** [comment]
Can you tell me your Forge version and what version of SimpleHammers you are using?

**Comment by ndbn** [comment]
Yeah,
forge-1.12.2-14.23.1.2600-universal.jar
simplehammers-1.12.2-1.1.0.1.jar

config is default

**Comment by DaemonUmbra** [comment]
I'm afraid I can't reproduce the issue, nor can I see how this is happening. May I ask why your server is running in offline mode?

**Comment by ndbn** [comment]
Custom server fo me and friends. I've added Sponge Mod to server and seems like there are no more non critical exceptions and crashes, I will test also for 24 hrs.

**Comment by ndbn** [comment]
Nevertheles, but I am not shure, rayTrace can return null. 
Return value checked before using:
for ex.:
https://github.com/SlimeKnights/TinkersConstruct/blob/08f7180399ca8ad4717493dd0aa5a63b7aa14584/src/main/java/slimeknights/tconstruct/gadgets/item/ItemSlimeSling.java#L76

**Comment by DaemonUmbra** [comment]
In this instance the RayTrace should NEVER be null, can you send me an actual crash report instead of a log?

**Comment by DaemonUmbra** [comment]
Can you test it again with version 1.1.0.2 and send me logs?

**Comment by ndbn** [comment]
Yes, I'll try. Honestly after I install Sponge and configure garbage collector parameters like recommended Aikar, there was no more critical faults and crashes, only rare console-level exceptions.
I updating all mods now and then will send you logs on next week. 
Thanks for commit.

**Comment by ndbn** [comment]
No failures and no log messages from SimpleHammers. 
I tried to run version without Sponge and with old java garbage collector(CMS) for emulate old situation but there was no log messages. 
I think this issue can be closed...
